cause = ['[player] was squashed by a falling anvil',
'[player] was pricked to death',
'[player] walked into a cactus whilst trying to escape [player2]',
'[player] was shot by arrow',
'[player] drowned',
'[player] drowned whilst trying to escape [player2]',
'[player] blew up',
'[player] was blown up by [player2]',
'[player] hit the ground too hard',
'[player] fell from a high place',
'[player] fell off a ladder',
'[player] fell off some vines',
'[player] fell out of the water',
'[player] fell into a patch of fire',
'[player] fell into a patch of cacti',
'[player] was doomed to fall',
'[player] was doomed to fall by [player2]',
'[player] was shot off some vines by [player2]',
'[player] was shot off a ladder by [player2]',
'[player] was blown from a high place by [player2]',
'[player] went up in flames',
'[player] burned to death',
'[player] was burnt to a crisp whilst fighting [player2]',
'[player] walked into a fire whilst fighting [player2]',
'[player] was slain by [player2]',
'[player] was shot by [player2]',
'[player] was fireballed by [player2]',
'[player] was killed by [player2] using magic',
'[player] tried to swim in lava',
'[player] tried to swim in lava while trying to escape [player2]',
'[player] died',
'[player] was squashed by a falling block',
'[player] was shot by [player2]',
'[player] was killed by [player2] using magic',
'[player] was killed by magic',
'[player] starved to death',
'[player] suffocated in a wall',
'[player] was killed while trying to hurt [player2]',
'[player] was pummeled by [player2]',
'[player] fell out of the world',
'[player] fell from a high place and fell out of the world',
'[player] was knocked into the void by [player2]',
'[player] withered away'].sample.sub('[player]', ARGV[2..-1].join(' ')).sub('[player2]', ARGV[0])

puts cause
